---
sudo: false

language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

matrix:
  allow_failures:
    - php: '7.1'
    - php: '7.2'
  fast_finish: true

git:
  depth: 1

install:
  - composer install

script:
  - vendor/bin/phpunit -c phpunit.xml.dist
  - vendor/bin/phpcs --standard=psr2 src
...
